# Generated by Django 5.1.4 on 2025-04-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fooItem',
            new_name='foodItem',
        ),
    ]
