# Generated by Django 5.1.4 on 2025-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_slug'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(fields=('vendor', 'category', 'slug'), name='unique_sulg_per_vendor_and_category'),
        ),
    ]
