# Generated by Django 5.1.4 on 2025-04-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_fooditem_unique_sulg_per_vendor_and_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodItems', to='menu.category'),
        ),
    ]
